spring:
  application:
    name: Config-Produc

eureka:
  instance:
    prefer-ip-address: true
client:
  feth-registry: true
  register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka


